### ISSUE TITLE
getbalance always 0

### ISSUE THREAD

**Issue by kawww** [kevacoin-project/kevacoin#14]
I use getbalance address to check keva, but it seems alway 0.0000

**Comment by kevacoin-project** [comment]
The block maturity is 100 blocks. If you mine a block, it will take another 100 blocks for the reward to show up in your wallet.

However, if you transfer KVA from another address, the balance should show up in the next block (assume the tx is included in the next block).

**Comment by kawww** [comment]
> The block maturity is 100 blocks. If you mine a block, it will take another 100 blocks for the reward to show up in your wallet.
> 
> However, if you transfer KVA from another address, the balance should show up in the next block (assume the tx is included in the next block).

Thanks for the reply.

I check three addresses, every address have kva, one is from day1 till now, no problem.

I found getbalance only support to show total kva and account kva, not support address kva. That's why I use getbalance address it shows 0 because no account called this address name.
