### ISSUE TITLE
Content research

### ISSUE THREAD

**Issue by ghost** [kevacoin-project/kevacoin#20]
Hello, 

how can I find served key/values in the blockchain? Is there any API or third-party namespaces explorer there?

**Comment by kawww** [comment]
It seems no this tool now.

There are many way to read key/values in the blockchain.

For example: get every tx contents include "OP_KEVA_NAMESPACE", use keva_filter NAMESPACE to get every contens.

code 

https://github.com/kevacoin-toolkit/block-viewer

**Comment by ghost** [comment]
Thank you!

**Comment by d47081** [comment]
https://github.com/kvazar-network
