### ISSUE TITLE
How can I get _KEVA_NS_ value from the raw transaction?

### ISSUE THREAD

**Issue by ghost** [kevacoin-project/kevacoin#22]
I need to decode _KEVA_NS_ value, but without local node running.

How can decode the raw transaction using [Kevacoin Explorer API](https://explorer.kevacoin.org/api/getrawtransaction?txid=597cc2ca602be23ecaf6e0c27ab9d712245ea5eba8b6d65da9f28cca56650cb3&decrypt=1) to replace keva_get method:

```
$hash = Base58Check::encode('356a893ac5dbc64229a0700d63b019c72e5227644d', false , 0 , false);
$nameSpace = $node->keva_get($hash, '_KEVA_NS_');

```

Thanks.

**Comment by kevacoin-project** [comment]
Sorry for the late reply. "_KEVA_NS_" key doesn't really exist. It is a pseudo key, whose value is <display_name> as in the namespace creation command `keva_namespace <display_name>`.

If you want to get the <display_name>, you can get the it from the [tx which contains the namespace creation](https://explorer.kevacoin.org/api/getrawtransaction?txid=c2d9c927bb3a3819325242c6e19fd99644204a334a7967d3cced2a48a5d2cb8d&decrypt=1).

Look for:
```
OP_KEVA_NAMESPACE 35fd152e7cf52109d28d060cab2a7cccfd669cebc7 4b657661636f696e20446562757473204f6666696369616c204d6173636f7420392f3130
```
The `4b657661636f696e20446562757473204f6666696369616c204d6173636f7420392f3130` is the value of `_KEVA_NS_`.

**Comment by ghost** [comment]
Thank you.

p.s. may be decoded using `hex2bin` function in PHP.
