### ISSUE TITLE
Wallet sync seems to be slow

### ISSUE THREAD

**Issue by kevacoin-project** [kevacoin-project/kevacoin#6]
We received reports from some users that Kevacoin wallet sync was slow.

Steps to reproduce (command line):

1. Make sure the Kevacoin data directory is clean (do not accidentally delete your wallet.dat), so that the wallet will sync from the beginning.
2. On one console, run `kevacoind`.
3. On the other console, run `kevacoin-cli getblockcount`. This command returns after a long period of time.

On GUI wallet, the `connecting to peers ...` message last for a long time.

**Comment by kevacoin-project** [comment]
Part of the reason wallet sync is slow (at least it seems that way) is because Kevacoin uses Cryptonight R hash algorithm. A good and modern CPU may process about 50 - 100 hashes per second. The wallet sync starts with block header download, and the wallet needs to verify the headers. E.g. a short blockchain with 10000 block headers may take up to 100 - 200 seconds to process.

Maybe like Monero, we need to show some process information.

**Comment by markg85** [comment]
Note that the sync process (i'm in the middle of it right now) uses only one core and seems to be doing:
Download -> process -> download -> process, etc...

It would be much more efficient to download as much as you can and use all the available cpu cores.
That would probably improve syncing speed massively!

Also, i think the litecoin wallet (where this kavacoin one was forked from) is improved a lit already. See here where a user claims that: https://www.reddit.com/r/litecoin/comments/7m0ler/how_long_should_my_wallet_take_to_sync/
So you might need to update the codebase (if that is still possible) to benefit "for free" basically :)
